name: "Bug Report (Beta)"
title: "[Bug] - Title"
description: Report bugs on the website (using the new GitHub form issue).
labels: ["bug"]
assignees: ["Froxcey", "AZProductions"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **Are you looking for development help?**
        ↩ We don't provide development help here. Please search for help on Google, Stack Overflow, or our [Discord server](https://discord.gg/avdanos).

        **Do you have a question?**
        ↩ Please ask it on our [Discord server](https://discord.gg/avdanos)

        **Does your issue already exist?**
        ↩ Please search for existing issue before making a new one.

        **Is your issue about feature request or grammar/translation?**
        ↩ Submit a different type of issue on the _issue_ tab.

        **Is your issue about another repository?**
        ↩ Please only submit issues related to the website here. Issues related to the documentation should be submitted on the [docsite repositoy](https://github.com/Avdan-OS/Docsite).

        **Need help with a browser?**
        🙋 To get help with [Firefox](https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla), [Chrome](https://support.google.com/chrome/answer/95315?hl=en-GB&ref_topic=7439544), [Safari](https://www.apple.com/feedback/safari.html), or another browser, check the browser's support site.

        ---
  - type: checkboxes
    id: browser
    attributes:
      label: Please select the browsers that you have tested this issue on.
      options:
        - label: Safari, any iOS browser (Webkit)
        - label: Firefox, Tor (Gecko+Quantum)
        - label: Chrome, Brave, Edge, Opera (Chromium)
  - type: checkboxes
    id: latest
    attributes:
      label: Please make sure your browsers is maintained and up to date
      options:
        - label: Yes, my browser is maintained and up to date
          required: true
  - type: checkboxes
    id: os
    attributes:
      label: Please select the operating system that you have tested this issue on.
      options:
        - label: Linux based (Debian, Ubuntu, Arch, Fedora etc.)
        - label: MacOS
        - label: Windows
  - type: textarea
    id: hardware
    attributes:
      label: Please put your hardware/model information here.
  - type: textarea
    id: details
    attributes:
      label: Please explain what went wrong.
      description: Please include as much information as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please list pages that this issue is related to.
  - type: dropdown
    attributes:
      label: What do you think could be the potential cause of the issue?
      options:
        - Unknown
        - Front end (Browser compatibility)
        - Back end (React/NextJS)
        - System error (VPS problem)
        - Other
  - type: textarea
    id: references
    attributes:
      label: Provide us links that can help us fix this issue, if you have any.
      description: Ex. Any release notes, caniuse, bugs, pull requests, or MDN pages
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, screenshots, screen recordings, or sample code
  - type: checkboxes
    id: duplicate
    attributes:
      label: Please make sure this issue is not a duplicate of an existing issue.
      options:
        - label: Yes, I have search for this issue on this repository and none were found
          required: true
  - type: markdown
    attributes:
      value: |
        Thank you for filling this bug report, and we will try to respond as soon as possible.
