name: "Bug Report (Beta)"
title: "[Bug] - Title"
description: Report bugs on the website (using the new form GitHub feature).
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **Are you looking for development help?**
        ↩ We don't provide development help here. Please search for help on Google, Stack Overflow, or our [Discord server](https://discord.gg/avdanos).

        **Do you have a question?**
        ↩ Use the _community_ tab to ask questions.

        **Does your issue already exist?**
        ↩ Please search for existing issue before making a new one.

        **Is your issue about feature request or grammar/translation?**
        ↩ Submit a different type of issue on the _issue_ tab.

        **Is your issue about another repository?**
        ↩ Please only submit issues related to the website here. Issues related to the documentation should be submitted on the [docsite repositoy](https://github.com/Avdan-OS/Docsite).

        **Need help with a browser?**
        🙋 To get help with [Firefox](https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla), [Chrome](https://support.google.com/chrome/answer/95315?hl=en-GB&ref_topic=7439544), [Safari](https://www.apple.com/feedback/safari.html), or another browser, check the browser's support site.

        ---
  - type: checkboxes
    id: browser
    attributes:
      label: Tested on
      description: Please select the browsers that you have tested the issue on.
      options:
        - label: Safari, any iOS browser (Webkit)
        - label: Firefox, Tor (Gecko+Quantum)
        - label: Chrome, Brave, Edge, Opera (Chromium)
  - type: checkboxes
    id: latest
    attributes:
      label: Please make sure your browser is maintained and up to date
      options:
        - label: Yes, my browser is maintained and up to date
          required: true
  - type: textarea
    attributes:
      label: What page(s) does this issue affect?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What could be a potential cause of the issue?
      options:
        - Unknown
        - Front end (Browser compatibility)
        - Back end (React/NextJS)
        - System error (VPS problem)
        - Other
  - type: textarea
    id: details
    attributes:
      label: Explain what went wrong
  - type: textarea
    id: tested
    attributes:
      label: Did you test this? If so, how?
  - type: textarea
    id: references
    attributes:
      label: Provide us links that can help us fix this issue, if you have any.
      description: Ex. any release notes, caniuse, bugs, pull requests, or MDN pages
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, screenshots, screen recordings, or sample code
  - type: checkboxes
    id: duplicate
    attributes:
      label: Please make sure this issue is not a duplicate of an existing issue.
      options:
        - label: Yes, I have search for this issue on this repository and none were found
          required: true
